### ISSUE TITLE
Missing parts

### ISSUE THREAD

**Issue by anatoliyarkhipov** [prezly/prop-types-php#2]
I tried it in my project and it does fit my use-case. The only parts missing are those methods:
- [x] https://github.com/prezly/prop-types-php/pull/3 `PropTypes::shape()`
- [x] `PropTypes::oneOf()`
- [x] `PropTypes::oneOfType()`

Wouldn't you mind if I implement them and send in a separate PR each?

- - -

Also, what do you think of this two changes:
1. To not throw on extra props
2. To expose functions along with static methods so it's also possible to write declarations like this:
```php
        $context = [
            "response" => shape([
                "total" => int()->isRequired(),
                "books" => arrayOf(
                    shape([
                        "isbn"   => string()->isRequired(),
                        "title"  => string()->isRequired(),
                        "rating" => int()->isRequired(),
                        "author" => string()->isRequired(),
                    ])
                )->isRequired()
            ]),
        ],
```

**Comment by e1himself** [comment]
> Wouldn't you mind if I implement them and send in a separate PR each?

Oh, we would appreciate any contribution! So feel free to. :+1:

> 1. To not throw on extra props

AFAIK this is achieved in JS Prop-Types by having two shape validators: `shape()` and `exact()`.
So the plan was to also implement both of them in this repo as well:

- `shape()` &mdash; `ShapeTypeChecker`
- `exact()` &mdash; `StrictShapeTypeChecker`

> 2. To expose functions along with static methods so it's also possible to write declarations like this

I'm not a big fan of this to be honest. For a few reasons:

- these function names are too generic (so it's difficult to tell what do they do just by looking at user-land code) -- you have to watch closer
- these function names are matching native type names/keywords (though I know it's OK now in the new PHP versions)
- `PropTypes::string()` also maps 1-to-1 with JS-world implementation. So it's more familiar to people.

That being said, I would not want to add these functions to this repo. However, you can rather easily achieve the same result by publishing a wrapper package that adds these functions on top of the stock static class methods.

Cheers.

**Comment by e1himself** [comment]
I've also created separate issues for every one of missing methods. So we can close them with PRs one-by-one :)

- `PropTypes::shape()` - #4 
- `PropTypes::exact()` - #5 
- `PropTypes::oneOf()` - #6 
- `PropTypes::oneOfType()` - #7 
- `PropTypes::callback()` - #8

**Comment by e1himself** [comment]
> To not throw on extra props

Oh, now I understand what you mean. The top-level `PropTypes::checkPropTypes()`, right?

**Comment by anatoliyarkhipov** [comment]
Wow, you're fast! 😁

> Oh, now I understand what you mean. The top-level PropTypes::checkPropTypes(), right?

Yes, I meant exactly this function. As far as I can judge, PR #14 solves this.
